### ISSUE TITLE
bug:一些测试出来的小问题集合

### ISSUE THREAD

**Issue by RyanHo97** [tangllty/tang-boot#3]
1. 在线用户没能成功返回数据。
2. 注册新账号然后删除，再次注册无法登录。

**Comment by tangllty** [comment]
问题一已修复
https://github.com/tangllty/tang-boot/commit/29b2ca8d6bd516d831172155e4574c44af318b72

**Comment by tangllty** [comment]
问题二可以说一下复现步骤吗

**Comment by tangllty** [comment]
新增用户校验已添加
https://github.com/tangllty/tang-boot/commit/83eb58c9a0db8aa98f4af2272c680f331404feed

**Comment by tangllty** [comment]
问题二已修复
https://github.com/tangllty/tang-boot/commit/2d08a8bc3d1374449d9810b6795c84c01d4843d5
